- package-lock.json
- package.json
- src/DEOK/Login_SingUp/Login_Signup.jsx
- src/GUN/SocialKakao.jsx
- src/Routing.jsx
> KakoLogin (연결만)

- src/GUN/SocialKakao.jsx
> Add Redirect URI

- src/YEON/planMain.module.css
> remove background color

- src/GUN/components/PackageFoot.jsx
- src/GUN/components/PackageFoot.module.css
> packageFoot

- src/GUN/Package_Detail_Style.css
- src/GUN/components/PackageFoot.jsx
- src/GUN/components/PackageFoot.module.css
- src/GUN/components/payment.jsx
- src/GUN/components/payment.module.css
packageDetail css almost complete
> packageDetail css almost complete

- src/GUN/components/PackageFoot.jsx
> Add scroll style

- src/GUN/PackageList.jsx
- src/GUN/PackageList.module.css
- src/Routing.jsx
> Package connect spring & DB

- src/GUN/PackageList.jsx
- src/GUN/PackageList.module.css
> 패키지 리스트 필터 및 리스트 요소 정리

- src/GUN/PackageIndex.jsx
- src/GUN/components/PackageBody.jsx
- src/GUN/components/PackageBody.module.css
- src/GUN/components/PackageFoot.jsx
- src/GUN/components/PackageHead.jsx
- src/GUN/components/PackageHead.module.css
> Add package body table

- src/GUN/RentCarList .jsx
- src/GUN/components/RentCarFoot.jsx
- src/GUN/components/RentCarFoot.module.css
- src/GUN/components/RentCarHead.jsx
- src/Routing.jsx
connect rentcar react=>springboot
> connect rentcar react=>springboot

- src/Hye/advertisement.jsx
> 인터벌로 인한 axios오류제거

- src/CKH/Components/AirCard/Card.css
- src/CKH/Components/AirCard/Product.jsx
> 항공 카드 이미지 CSS수정

- src/CKH/Components/Navbar/Navbar.jsx
- src/GUN/RentCarList .jsx
- src/GUN/RentCarList.module.css
- src/Routing.jsx
> 렌트카 리스트 연동성공

- src/GUN/PackageList.jsx
- src/GUN/PackageList.module.css
리액트user/패키지 리스트 서치필드 적용+필터박스 기능/스타일 변경 커밋합니다.
> 리액트user/패키지 리스트 서치필드 적용+필터박스 기능/스타일 변경 커밋합니다.

- src/GUN/components/PackageFoot.jsx
- src/GUN/components/PackageHead.jsx
- src/Routing.jsx
> 리액트user/ 패키지디테일 스프링연동

- src/GUN/PackageList.jsx
- src/Hye/machineList.jsx
> 리스트에 광고 추가

- src/GUN/PackageList.jsx
- src/GUN/components/PackageHead.jsx
- src/GUN/components/RentCarFoot.jsx
- src/GUN/components/RentCarFoot.module.css
- src/GUN/components/RentCarHead.jsx
리액트user/ 렌트카 헤드, 리스트, 패키지 헤드, 리스트 여러가지 추가 충돌수정 커밋합니다.
> 리액트user/ 렌트카 헤드, 리스트, 패키지 헤드, 리스트 여러가지 추가 충돌수정 커밋합니다.

- src/GUN/RentCarList .jsx
- src/GUN/components/PackageHead.module.css
- src/GUN/components/RentCarFoot.jsx
- src/GUN/components/RentCarFoot.module.css
리액트user/패키지 디테일 사진 크기 오류 수정, 렌트카 디테일 규격 조정 렌트카 디테일 수정
> 리액트user/패키지 디테일 사진 크기 오류 수정, 렌트카 디테일 규격 조정 렌트카 디테일 수정

- src/GUN/PackageList.jsx
> 머신러닝 광고 커밋

- src/GUN/PackageIndex.jsx
- src/GUN/components/PackageFoot.jsx
- src/GUN/components/PackageHead.module.css
> 패키지 투어 디버깅

- src/GUN/RentCarList .jsx
> 랜터카리스트정렬수정

- src/CKH/Components/AirCard/Card.css
- src/CKH/Components/AirCard/Card.jsx
- src/CKH/Components/AirCard/Product.css
- src/CKH/Components/AirCard/Product.jsx
- src/CKH/Components/Card/Card.css
- src/CKH/Components/Card/Card.jsx
- src/CKH/Components/Card/Product.css
- src/CKH/Components/Card/Product.jsx
- src/CKH/Components/Navbar/navbar.css
- src/CKH/Components/Offers/Offers.jsx
- src/CKH/Components/Offers/offers.css
- src/CKH/Components/PakCard/Card.jsx
- src/CKH/Components/PakCard/Product.jsx
- src/CKH/Components/hotelCard/Card.jsx
- src/CKH/Components/hotelCard/Product.jsx
- src/Hye/mcAdvertisementComponent.scss
> 메인페이지 4차 수정

- src/DEOK/Login_SingUp/Login_Signup.jsx
> 로그인 설문 조사폼

- src/CKH/Components/Navbar/Navbar.jsx
- src/CKH/Components/Navbar/navbar.css
- src/CKH/Components/Offers/offers.css
> 디버깅 26번 해결

- src/CKH/Components/AirCard/Card.css
- src/CKH/Components/Footer/footer.css
- src/CKH/Components/Hero/Hero.css
- src/CKH/Components/Hero/Hero.jsx
- src/CKH/Components/NewBanner/NewBanner.css
- src/CKH/Components/Offers/offers.css
> 디버깅 20번 21번 해결완료

- src/CKH/Components/Navbar/Navbar.jsx
> navbar 조인 로그아웃 아이콘 겹치는거 수정

- src/CKH/Components/Navbar/navbar.css
> navbar 호버시 색상 변경

- src/CKH/Components/Hero/Hero.css
> 메인페이지 영상짤리던것 수정
